swagger: "2.0"
info:
  title: beego Test API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /reportes/desagregado:
    post:
      tags:
      - reportes
      description: post Desagregado
      operationId: ReportesController.Desagregado
      parameters:
      - in: body
        name: body
        description: body for Plan content
        required: true
        schema:
          $ref: '#/definitions/{}'
      responses:
        "201":
          description: ""
          schema:
            $ref: '#/definitions/models.Reportes'
        "403":
          description: :plan_id is empty
  /reportes/necesidades/{nombre}:
    post:
      tags:
      - reportes
      description: post Necesidades
      operationId: ReportesController.Necesidades
      parameters:
      - in: body
        name: body
        description: body for Plan content
        required: true
        schema:
          $ref: '#/definitions/{}'
      - in: path
        name: nombre
        description: The key for staticblock
        required: true
        type: string
      responses:
        "201":
          description: ""
          schema:
            $ref: '#/definitions/models.Reportes'
        "403":
          description: :plan_id is empty
  /reportes/plan_anual/{nombre}:
    post:
      tags:
      - reportes
      description: post PlanAccionAnual
      operationId: ReportesController.PlanAccionAnual
      parameters:
      - in: body
        name: body
        description: body for Plan content
        required: true
        schema:
          $ref: '#/definitions/{}'
      - in: path
        name: nombre
        description: The key for staticblock
        required: true
        type: string
      responses:
        "201":
          description: ""
          schema:
            $ref: '#/definitions/models.Reportes'
        "403":
          description: :plan_id is empty
  /reportes/plan_anual_evaluacion/{nombre}:
    post:
      tags:
      - reportes
      description: post PlanAccionEvaluacion
      operationId: ReportesController.PlanAccionEvaluacion
      parameters:
      - in: body
        name: body
        description: body for Plan content
        required: true
        schema:
          $ref: '#/definitions/{}'
      - in: path
        name: nombre
        description: The key for staticblock
        required: true
        type: string
      responses:
        "201":
          description: ""
          schema:
            $ref: '#/definitions/models.Reportes'
        "403":
          description: :nombre is empty
  /reportes/plan_anual_general/{nombre}:
    post:
      tags:
      - reportes
      description: post PlanAccionAnualGeneral
      operationId: ReportesController.PlanAccionAnualGeneral
      parameters:
      - in: body
        name: body
        description: body for Plan content
        required: true
        schema:
          $ref: '#/definitions/{}'
      - in: path
        name: nombre
        description: The key for staticblock
        required: true
        type: string
      responses:
        "201":
          description: ""
          schema:
            $ref: '#/definitions/models.Reportes'
        "403":
          description: :plan_id is empty
  /reportes/validar_reporte:
    post:
      tags:
      - reportes
      description: post ValidarReporte
      operationId: ReportesController.ValidarReporte
      parameters:
      - in: body
        name: body
        description: body for Plan content
        required: true
        schema:
          $ref: '#/definitions/{}'
      responses:
        "201":
          description: ""
          schema:
            $ref: '#/definitions/models.Reportes'
definitions:
  '{}':
    title: '{}'
    type: object
  models.Reportes:
    title: Reportes
    type: object
tags:
- name: reportes
  description: |
    ReportesController operations for Reportes
